spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to GeoBank accounts related prod Apis"
  contactDetails:
    name: "Elijah Oladapo"
    email: "toktogift@gmail.com"
  onCallSupport:
    - (+234) 814 7014 759